courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns =[
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name ='step'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name ='detail'),
]

untitled/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django_start.views import hello_world
from courses import views

from courses import urls

urlpatterns = [
    url(r'^courses/', include('courses.urls',namespace='courses')),
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^',hello_world,name='hello_world'),
]

urlpatterns+= staticfiles_urlpatterns()

courses/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    content = models.TextField(blank=True,default='')

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title

django_start/models.py
from django.db import models

# Create your models here.

courses/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,render
from .models import Course,Step #.models adica fisierul models din folderul curent

# Create your views here.

def course_list(request):
    courses = Course.objects.all()
#    output = ', '.join([str(course) for course in courses])
#    return HttpResponse(output)
    email = 'intrebari_si_de-alea@ovidiu.ro'
    return render(request,'courses/course_list.html',{'courses':courses,'email':email})

def course_detail(request,pk):
    #course = Course.objects.get(pk = pk)
    course = get_object_or_404(Course,pk = pk)
    return render(request,'courses/course_detail.html',{'course': course})

def step_detail(request,course_pk,step_pk):
    step = get_object_or_404(Step,course_id=course_pk,pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

django_start/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def hello_world(request):
    #return HttpResponse("SAAL")
    return render(request,'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% load humanize %}    {# de la installed_apps humanize #}
{% load course_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
            {{ course.title }}
            {% endblock %}
    </title>
</head>
<body>
    {% block content %}
    <article>
    <h2>
        {{ course.title }}
    </h2>
        {{ course.description|markdown_to_html }}  {# safe filter-html to normal text #}

        <p>There are {{ course.step_set.all.count|apnumber }} step{{ course.step_set.count|pluralize }}.</p> {# |length-causes a large database query to be run; folosim .count;apnumber-letters #}
        <p>These are the steps in this course: {{ course.step_set.all|join:", " }}</p> {#join- ca sa nu mi-l dea ca <QuerySet [<Step: Using the shell>, <Step: Stringuri si de-alea>]> #}
    <section>
        {% for step in course.step_set.all %}
            <h3><a href="{%  url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}" >{{ step.title }}</a></h3>
            {{ step.description }}
        {#     <h2>There are {% conjugate_is() %} </h2>#}
        {% endfor %}
    </section>
    </article>
    {% endblock %}
</body>
</html>

courses/templates/courses/course_list.html
{%  extends "layout.html" %}
{% load static from staticfiles %}


{% block static%} <link rel="stylesheet" href="{% static 'courses/css/courses.css'%}">{% endblock%} {# customizing templates lecture 2 #}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Chestii cu stouri {% endblock %}</title>
</head>
<body>
{% block content %}
    <div class="cards">
    {% for course in courses %}
        <div class ="card">
        <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a> </header>
        <div class ="card-copy">
            {% if course.description|wordcount <= 5 %}
            {{ course.description }}
                {% else %}
                {{ course.description|truncatewords:5 }}  {# afiseaza doar primele 5 #}
                <a href="{% url 'courses:detail' pk=course.pk %}">Read more</a>
            {% endif %}
            <div>Created on: {{ course.created_at|date:"F j, Y" }}</div>
        </div>
        </div>
        {% endfor %}
        <div>Have any questions? Contact us! {# poate fi inlocuit cu<a  href="mailto:{{ email }} ">#}{{ email|urlize }} </div>
        </div>
{% endblock %}
</body>
</html>

courses/templates/courses/course_nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for course in courses %}
        <div><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></div>
    {% endfor %}
</body>
</html>

courses/templates/courses/step_detail.html
{% extends "layout.html" %}
{% load course_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
            {{ step.title }} - {{ step.course.title }}
            {% endblock %}
    </title>
</head>
<body>
{% block content %}
<article>
    <h2>
        <a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a>
    </h2>
    <h3>{{ step.title }}</h3>
    {% with con=step.content %}         {# con-variabila #}
        {{ con|linebreaks }} Content: {{ con|wordcount }} words.
        Approximated time to finish: {{ con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}.
    {% endwith %}
</article>
{% endblock %}
</body>
</html>

templates/home.html
{% extends "layout.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Homepage {% endblock %}</title>
</head>
<body>
    {% block content %}
    <h1>Salutare</h1>
    {% endblock %}

</body>
</html>

templates/layout.html
{% load static from staticfiles %}
{% load course_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css'%}">
    {% block static %} {% endblock %}
</head>
<body>
    <div class = "site-container">
    <div>{% nav_courses_list %}</div>
    <nav>
        <a href="{% url 'hello_world' %}">Home</a>
        <a href="{% url 'courses:list' %}">Courses</a>
    </nav>
        <p>Don't miss our latest course,
            "{% newest_course %}"!</p>
    {% block content %}{% endblock %}
    </div>
</body>
</html>